[package]
name = 'CetusClmm'
version = '0.0.2'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
dexlyn_clmm = "0xa7f01413d33ba919441888637ca1607ca0ddcbfa3c0a9ddea64743aaa560e498"
integer_mate = "0xa7f01413d33ba919441888637ca1607ca0ddcbfa3c0a9ddea64743aaa560e498"
aptos_token_objects = "0x4"

# [dependencies.SupraFramework]
# git = 'https://github.com/Entropy-Foundation/aptos-core.git'
# subdir = 'aptos-move/framework/supra-framework'
# rev = 'aptosvm-v1.16_supra-v0.4.0'

# [dependencies.AptosToken]
# git = 'https://github.com/Entropy-Foundation/aptos-core.git'
# subdir = 'aptos-move/framework/aptos-token'
# rev = 'aptosvm-v1.16_supra-v0.4.0'

[dependencies.AptosTokenObjects]
git ="https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"

# [dependencies.AptosStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-stdlib"
# rev = "mainnet"

# [dependencies.AptosFramework]
# git = 'https://github.com/aptos-labs/aptos-core.git'
# rev = 'testnet'
# subdir = 'aptos-move/framework/aptos-framework'

# [dependencies.AptosToken]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/aptos-token"
# rev = "testnet"

[dependencies.IntegerMate]
local = "../IntegerMate"