[package]
name = 'IntegerMate'
version = '1.0.0'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
integer_mate = "0xa7f01413d33ba919441888637ca1607ca0ddcbfa3c0a9ddea64743aaa560e498"

# [dependencies.SupraFramework]
# git = 'https://github.com/Entropy-Foundation/aptos-core.git'
# subdir = 'aptos-move/framework/supra-framework'
# rev = 'aptosvm-v1.16_supra-v0.4.0'

# [dependencies.MoveStdlib]
# git = "https://github.com/aptos-labs/aptos-core.git"
# subdir = "aptos-move/framework/move-stdlib"
# rev = "testnet"